max_retries: 3
timeout: 10
max_content_size: 131072  # 128KB in bytes
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
follow_redirects: true
rate_limit: 50
time_window: 60 